name: Publish to NPM
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run rollup
      - name: Extract tag version
        id: extract_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      - name: Update version in package.json
        run: |
          npm --no-git-tag-version version ${{ steps.extract_tag.outputs.VERSION }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: bump version to ${{ steps.extract_tag.outputs.VERSION }}"
          git push origin HEAD:main
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
